import { Component, OnInit } from '@angular/core';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent {
    getRandomColor = () => {
        let r = Math.floor(Math.random() *256);
        let g = Math.floor(Math.random() *256); 
        let b = Math.floor(Math.random() *256);
        return 'rgb(' + r + ',' + g + ',' + b + ')'; 
    }

  projectsList = [
    {projectName:"CoE Team Initiation Setup and Launch",
    projectDesc:"",
    color: this.getRandomColor()
    },
	{projectName:"Ways of working - Building an Integrated cyber security team",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Universal Data lake - Data ingestion - I&A",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"KFAS, CJ - Crown Jewel Process ",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"ETP - Risks and Exemption Cleanup",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Security Assurance - Monthly Cadence",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Monthly Platform Cadence",
    projectDesc:"Consumer Engagement Customer Development, Consumer Operations, Consumer Experience and Performance, R&D, Leverage DMS, Go to Market",
    color: this.getRandomColor()},
	{projectName:"Security Metrics - Secure by Design, Org Managed Estate KPI Definition",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Cloud Migration Strategies",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Risk recon - Ponemon Report Research and Traceback",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"AWS, Azure, Salesforce - Cloud Assessment",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Covid 19 and Beyond - Redefining Technology Roadmaps",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Priority Systems - Asset Inventory Repository - Re-Evaluation - Reassessment - Fisk Residue - Fill Compliance Gap",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Platforms - Heat Map Project - Risk Posture",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"CMDB and ServiceNow Clean Up - Misalignment",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"CJ Audit Remediations, KFAS, PPD",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Factory - Augmented Reality Implementations",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"CiiC Centers - Establishment - Improvement of Consumer Experience Centers Marketing and Sales Centers",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Cyber Risk Breakdown ",
    projectDesc:"Geography Wise Category Wise, Inherent, Residual (Status), Platform Wise, Projectwise, Service Wise(Cloud, On Prem, M&A) Asset Based, Annual Loss Expectancy, Control Assessments Impact, ROI",
    color: this.getRandomColor()},
	{projectName:"Cyber Security Awareness - Training and Testing",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Gaming - Contest - Education",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:" Power BI - Executive Dashboards for CSPA - KPIs - Leader Wise, Platform Wise, Risk Wise",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Feedback Initiative Platform",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Devising Strategies for Risk Assessment Approach to Various Critical Assets of Organisation",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Technology Roadmap Integration for Business Platforms - Cyber Security",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"CoE Engagement Model - Redefining",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"API Integrations - Learning and Early Adaptations - Approach Defined from Gartner",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Application Vulnerability - Remediation",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Cyber Compliance Cockpit - PowerBI",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"DTC Customer - Websites - Exposed URLs - PT Oversee Compliance Management and PAG Status Review",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Redefining - Security Baseline Control with Evolving Technology",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Big Rocks and Iops - Promotion as a Service",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"WhatsApp - Integration for Sales and Marketing, Promotions",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"POCs, RFPs, Pilots, Tier 1 Advisory",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"eCommerce Platforms",
    projectDesc:"App Onboarding Assessment, Framework, Checklist based Easy Approach, Next step deep dive if higherrisk, Security assessment, Legal Assessment for further Evaluation and Approach",
    color: this.getRandomColor()},
	{projectName:"Cloud based Services - Content Security Policy Implementation and Exemptions Challenges, Web Extensions",
    projectDesc:"",
    color: this.getRandomColor()},
	{projectName:"Project Aurora - Leveraged DMS, Salesforce and Trade Promotion Management Platform Integration",
    projectDesc:"",
    color: this.getRandomColor()},
  ];
}
